# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf7696cac63473663b098f14014a311cfce45d872381716155f3bf16576cf1aa063acab95309d2567a72882b251134b958d6c7be6f6eb2880c849a474846d161

test:
  secret_key_base: 27c938f7d27cc3f6389ed0f38da41f1701acd92db8192328c794644d7bedf8047c133d329e273c684d35541bf6134c20467d618a9c745bf03cf057f3222420b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
